"""Renamed sub to id column in user table

Revision ID: c72a9443d123
Revises: 1344a6b346e7
Create Date: 2025-12-25 11:20:40.349976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72a9443d123'
down_revision: Union[str, Sequence[str], None] = '1344a6b346e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'google_sub')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_sub', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=False)
    op.drop_column('users', 'id')
    # ### end Alembic commands ###
