"""added created_at column in agent_faithfullness table

Revision ID: d9627f7a2e62
Revises: 111db30f6d52
Create Date: 2025-12-29 09:55:36.121144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9627f7a2e62'
down_revision: Union[str, Sequence[str], None] = '111db30f6d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
