"""added que_to_generate column

Revision ID: fc1a9975d6ab
Revises: 4363af75175a
Create Date: 2025-12-29 17:46:33.628721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1a9975d6ab'
down_revision: Union[str, Sequence[str], None] = '4363af75175a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pii_registration', sa.Column('que_to_generate', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('pii_registration', 'que_to_generate')
    # ### end Alembic commands ###
